NAME = ft_display_file
SRC = ft_display_file.c
CC = gcc
FLAGS = -Wall -Wextra -Werror -o

all: $(NAME)

$(NAME):
	@$(CC) $(FLAGS) $(NAME) $(SRC)

clean:
	@rm -f *.o

fclean: clean
	@rm -f $(NAME)

re: fclean all